# Generated by Django 2.2.3 on 2023-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imageai', '0002_imagemodel_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagemodel',
            name='outputted_image',
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='analysed_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='imagemodel',
            name='input_image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
